create table tOrderStatus(
    osid int GENERATED BY DEFAULT AS IDENTITY,
    ordStatusDef varchar(10),
    ordStatusVal varchar(30),
    insertdate timestamp default now()
    )

insert into torderstatus(ordStatusDef, ordStatusVal)
values('Cancelled','CA'),('Ordered','OR'),('Shipped','SH')

select * from torderstatus