create table tCustAddr(
    caid int GENERATED BY DEFAULT AS IDENTITY,
    cid int REFERENCES tCustomer(cid),
    addr varchar(50) NOT NULL,
    city varchar(35) NOT NULL,
    zip varchar(12) NOT NULL,
    insertdate timestamp default now()
)