create table tOrder(
    oid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cid int REFERENCES tcustomer(cid),
    orddate timestamp default now(),
    shipdate timestamp,
    shipaddr varchar(50),
    shipcity varchar(35),
    shipzip varchar(12)
    )  