create table tproduct(
        prodid INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        prodname varchar(50) not null,
        price decimal(6,2),
    	description varchar (140),
    	insertdate TIMESTAMP DEFAULT NOW()
)


